### ISSUE TITLE
Upload folder visible

### ISSUE THREAD

**Issue by adjustGirl** [andrianvaleanu/WP-Maintenance-Mode#253]
Unfortunately I noticed that everything in the upload folder can still be accessed. Why can that be?
I've there 3 pdfs and everyone can see these.

**Comment by georgejipa** [comment]
@adjustGirl We never said that the upload folder (`/wp-content/uploads/`) would not be accessible when the plugin is activated.
For example, if you want to upload and display an image on the maintenance mode page, the upload directory must be accessible. Otherwise, the image would not work.
Also, (when it is active) the bot loads the settings file from the upload directory. Again, without it being accessible, the bot would not work.

So, if you want to block the uploads directory, WP Maintenance Mode is not the plugin you're looking for.
